---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  use_vagrant_berkshelf_plugin: true
  customize:
    memory: 2048
    cpus: 2
  network:
        - ["forwarded_port", {guest: 4444, host: 4444}]

provisioner:
  name: chef_zero
  data_path: test/shared
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[selenium-cluster::hub]
      - recipe[selenium-cluster::node]

  - name: phantomjs
    run_list:
      - recipe[selenium-cluster::hub]
      - recipe[selenium-cluster::phantomjs]

