name 'selenium-cluster'
maintainer 'Vlad Alyukov'
maintainer_email 'valyukov@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures Selenium WebDriver Grid2/Node/PhantomJS'
version '0.9.27'

supports 'ubuntu', '>= 12.04'
supports 'ubuntu', '>= 14.04'

depends 'java', '1.22.0'
depends 'phantomjs', '1.0.3'
depends 'ark', '~> 0.8.2'
depends 'google-chrome', '~> 0.0.1'
depends 'apt', '~> 2.3.10'
