Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-12.04-amd64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

  config.omnibus.chef_version = :latest
  config.berkshelf.enabled = true

  config.vm.customize ["modifyvm", :id, "--memory", 4096, "--cpus", 2]
  
  config.vm.forward_port 4444, 4444
  config.vm.provision :chef_solo do |chef|
      chef.add_recipe "selenium::hub"
      chef.add_recipe "selenium::node"
  end
end
